-- TABELA DE USUARIO

CREATE TABLE TUSUARIO (
	codigo BIGINT(20) NOT NULL,	
	NOME VARCHAR(50) NOT NULL,
	login VARCHAR(50) NOT NULL,
	senha VARCHAR(90) NOT NULL	
	PRIMARY KEY (codigoPessoa),	
	UNIQUE KEY (codigoPessoa)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- TABELA DE PERMISSÃO

CREATE TABLE TPERMISSAO (
    codigo BIGINT(20) PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR(200) NOT NULL,
    UNIQUE KEY (codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- TABELA DE GRUPO

CREATE TABLE TGRUPO (
    codigo BIGINT(20) PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    UNIQUE KEY (codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- TABELA DE GRUPO PERMISSAO

CREATE TABLE TGRUPOPERMISSAO (
    codgrp BIGINT(20) NOT NULL,
    codper BIGINT(20) NOT NULL,
    PRIMARY KEY (codgrp, codper),
    FOREIGN KEY (codgrp) REFERENCES TGRUPO(codigo),
    FOREIGN KEY (codper) REFERENCES TPERMISSAO(codigo),
    UNIQUE KEY (codgrp,codper)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- TABELA DE USUÁRIO GRUPO

CREATE TABLE TUSUARIOGRUPO (
    codusr BIGINT(20) NOT NULL,
    codgrp BIGINT(20) NOT NULL,
    PRIMARY KEY (codusr, codgrp),
    FOREIGN KEY (codusr) REFERENCES TUSUARIO(codigoPessoa),
    FOREIGN KEY (codgrp) REFERENCES TGRUPO(codigo),
    UNIQUE KEY (codusr,codgrp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;